### ISSUE TITLE
add error hint when vendir.yml is not found

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/vendir#12]
Many people create yaml files with either `yml` or `yaml` extensions. Vendir should look for both extensions (prioritizing maybe yml), so that it won't fail when the user creates a `vendir.yaml` file.

**Comment by cppforlife** [comment]
hmm, i think it's benefitial for a tool like this to support only one configuration file name since other tools that might want to interoperate with this file, so it would be awkward for them to implement various fallback options. also what would extension be for vendir.lock.yml? seems it gets quite complicated.

**Comment by jorgemoralespou** [comment]
The main problem with yaml is that extensions has not standardize to a single one. At least, if only want to support one, improve the message on the existence of the `.yaml` version  to something like:

```
Error: Reading config 'vendir.yml': open vendir.yml: no such file or directory. You should rename your 'vendir.yaml' file to 'vendir.yml'
```

It took me a while to realize that the extension was the problem as I was looking at the filename mostly.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/vendir/releases/tag/v0.10.0
