### ISSUE TITLE
Feature request: Automatic Releases on Merge to Master

### ISSUE THREAD

**Issue by osterman** [carvel-dev/vendir#26]
## what
* we rely on the binary releases to ship `vendir` in our https://github.com/cloudposse/packages
* these are published as alpine, debian (and soon rpm) packages 

## why
* we are blocked by not having a release for the bug fix contained in #22 

## references

Fwiw, here's how we do it:

* We automatically cut releases using this action: https://github.com/cloudposse/github-commenter/blob/master/.github/workflows/auto-release.yml
* We automatically build binary release artifacts using https://github.com/cloudposse/github-commenter/blob/master/.github/workflows/go.yml

**Comment by cppforlife** [comment]
> we are blocked by not having a release for the bug fix contained in #22

im happy to cut a release for you in this case.

> Feature request: Automatic Releases on Merge to Master

did you mean "master" or "develop" branch? if develop (our main development branch), i typically prefer to produce release with several features grouped together instead of just cutting release every time something is fixed to avoid having a "release fatigue" on the consuming side. obviously some folks have different appetite for consuming fast stream of releases (some are happy to pick up releases every hour) so being able to cut a release on demand is a good middle ground.

**Comment by cppforlife** [comment]
https://github.com/k14s/vendir/releases/tag/v0.13.0 includes #22 PR.

**Comment by aknysh** [comment]
thanks @cppforlife

**Comment by osterman** [comment]
@cppforlife lots of ways to do it, it's definitely more conventional to batch features into a release as you suggest. 

We practice a different strategy, that's evolved over time (not asking you to adopt it, just sharing it for context).

https://docs.cloudposse.com/community/faq/#what-is-our-versioning-strategy

It's similar to the policy that's been adopted for other projects, most notably `helmfile`.

The gist of it is that most users won't checkout your code and build it. Most users aren't probably Golang developers and have the environment setup. That means that the software will remain broken for most users when fixes are merged, or those who want to test the fixes can't test them. Instead every one should version pin for stability. Even "fixes" to bugs can be breaking workarounds for others. 

A variation of this would be to use pre-releases as a means of distributing changes more frequently.

Also, a frequently under appreciated feature of semver is that pre-1.0 (e.g. `0.x.0`) is [subject to change at any time](https://semver.org/#spec-item-4). =)

**Comment by cppforlife** [comment]
thanks for sharing info about your release process (carvel projects also follow semver, but sounds like you also opted into continuous releasing). it may change for us for time when current process becomes burdensome or doesnt scale as project matures.

ill close this issue for now since release was cut. we'll probably revisit topic of releasing in future in a larger scope than just vendir.
